version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

deployment:
  staging:
    branch: main
    heroku:
      appname: vast-garden-17209